version: 0.2

env:
   variables:
     REPOSITORY_URI: 077708451457.dkr.ecr.ap-south-1.amazonaws.com/node-app
     DOCKER_NAME: /ismailhi/MyDocker

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo pre_build - Logging in to Amazon ECR...
      - echo REPOSITORY_URI $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}   

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $DOCKER_NAME .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push /ismailhi/MyDocker      
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json